services:
  - type: web
    name: playlist-migrator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
